name: Build HubVelocityPlugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Ustaw Javę 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Ustaw Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10'

      - name: Zbuduj plugin
        run: gradle build

      - name: Udostępnij plik JAR
        uses: actions/upload-artifact@v4
        with:
          name: HubVelocityPlugin
          path: build/libs/*.jar
